# QFN DK (PCA10230) has only one UART connected to the debug bridge; use RTT for logging
CONFIG_LOG_BACKEND_UART=n

CONFIG_BT_HDT=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=510
CONFIG_BT_BUF_ACL_RX_SIZE=510
CONFIG_BT_BUF_ACL_TX_SIZE=510
CONFIG_BT_L2CAP_TX_MTU=506

CONFIG_BT_SDC_ADDITIONAL_MEMORY=8192